containers: add ansible-aws job

diff --git a/contrail-containers/ansible/aws-defs b/contrail-containers/ansible/aws-defs
--- a/contrail-containers/ansible/aws-defs
+++ b/contrail-containers/ansible/aws-defs
@@ -1,2 +1,14 @@
-echo "ERROR: aws deployment is not supported"
-exit 1
+export BUILD_NODE_TYPE=m4.large
+
+if [[ "$HA" == 'ha' ]]; then
+  export CONT_NODES=3
+elif [[ "$HA" == 'nonha' ]]; then
+  export CONT_NODES=1
+else
+  echo "ERROR: AIO deployment is not supported"
+  exit 1
+fi
+
+export CONT_NODE_TYPE=m4.xlarge
+export COMP_NODES=1
+export COMP_NODE_TYPE=c4.xlarge
