containers: exit with error for unsupported deployments

diff --git a/contrail-containers/kolla/server-defs b/contrail-containers/kolla/server-defs
--- a/contrail-containers/kolla/server-defs
+++ b/contrail-containers/kolla/server-defs
@@ -1,2 +1,5 @@
 export JOB_RND=$((RANDOM % 90 + 10))
 export NET_ADDR=${NET_ADDR:-"10.7.$JOB_RND.0"}
+
+echo "ERROR: server deployment is not supported"
+exit 1
