oshelm: initial env creation support

diff --git a/common/virsh/functions b/common/virsh/functions
--- a/common/virsh/functions
+++ b/common/virsh/functions
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -x
 
 function get_network_name() {
   local type=$1
@@ -65,6 +65,37 @@ function build_network_xml() {
   echo $fname
 }
 
+function build_network_xml_dhcp() {
+  local nname=$1
+  local network=$2
+  local forward_mode=${3:-'nat'}
+  local fname=`mktemp`
+  local net_base_ip=$(echo "$network" | cut -d '.' -f 1,2,3)
+  local nic_ip="${net_base_ip}.1"
+  local dhcp_start="${net_base_ip}.100"
+  local dhcp_end="${net_base_ip}.200"
+  cat <<EOF > $fname
+<network>
+  <name>$nname</name>
+  <bridge name="$nname"/>
+EOF
+  if  [[ "$forward_mode" == "nat" ]] ; then
+  cat <<EOF >> $fname
+  <forward mode="nat"/>
+EOF
+  fi
+  cat <<EOF >> $fname
+  <ip address="$nic_ip" netmask="255.255.255.0">
+    <dhcp>
+      <range start="$dhcp_start" end="$dhcp_end"/>
+    </dhcp>
+  </ip>
+</network>
+EOF
+
+  echo $fname
+}
+
 function delete_network() {
   local type="$1"
   local network_name=`get_network_name $type`
@@ -85,13 +116,32 @@ function create_network() {
   virsh net-start $network_name
 }
 
+function delete_network_dhcp() {
+  local network_name="$1"
+  virsh net-destroy $network_name 2> /dev/null || true
+  virsh net-undefine $network_name 2> /dev/null || true
+}
+
+function create_network_dhcp() {
+  local network_name=$1
+  local addr=$2
+  delete_network_dhcp $network_name
+  local fxml=$(build_network_xml $network_name $addr)
+  virsh net-define $fxml
+  rm -f $fxml
+  virsh net-autostart $network_name
+  virsh net-start $network_name
+}
+
 function create_pool() {
   local poolname="$1"
   local path="/var/lib/libvirt/$poolname"
-  virsh pool-define-as $poolname dir - - - - "$path"
-  virsh pool-build $poolname
-  virsh pool-start $poolname
-  virsh pool-autostart $poolname
+  if ! virsh pool-info $poolname &> /dev/null ; then
+    virsh pool-define-as $poolname dir - - - - "$path"
+    virsh pool-build $poolname
+    virsh pool-start $poolname
+    virsh pool-autostart $poolname
+  fi
 }
 
 function get_pool_path() {
@@ -100,7 +150,45 @@ function get_pool_path() {
   virsh pool-dumpxml $poolname | sed -n '/path/{s/.*<path>\(.*\)<\/path>.*/\1/;p}'
 }
 
-function _delete_domain() {
+function create_volume() {
+  local name=$1
+  local poolname=$2
+  local vm_disk_size=$3
+  delete_volume $name.qcow2 $poolname
+  local pool_path=$(get_pool_path $poolname)
+  qemu-img create -f qcow2 -o preallocation=metadata $pool_path/$name.qcow2 $vm_disk_size
+  echo $pool_path/$name.qcow2
+}
+
+function define_machine() {
+  local name=$1
+  local vcpus=$2
+  local mem=$3
+  local os=$4
+  local net=$5
+  local disk_path=$6
+  NET_DRIVER=${NET_DRIVER:-'e1000'}
+
+  virt-install --name $name \
+    --ram $mem \
+    --vcpus $vcpus \
+    --cpu SandyBridge,+vmx \
+    --os-variant $os \
+    --disk path=${disk_path},device=disk,cache=writeback,bus=virtio,format=qcow2 \
+    --network network=$net,model=$NET_DRIVER \
+    --noautoconsole \
+    --vnc \
+    --graphics vnc,listen=0.0.0.0
+    --dry-run --print-xml > /tmp/oc-$name.xml
+  virsh define --file /tmp/oc-$name.xml
+}
+
+function start_vm() {
+  local name=$1
+  virsh start $name --force-boot
+}
+
+function delete_domain() {
   local name=$1
   if virsh dominfo $name 2>/dev/null ; then
     virsh destroy $name || true
@@ -111,11 +199,11 @@ function _delete_domain() {
 
 function delete_domains() {
   for name in `virsh list --all | grep "rd-overcloud-$NUM-" | awk '{print $2}'` ; do
-    _delete_domain $name
+    delete_domain $name
   done
 
-  _delete_domain rd-undercloud-$NUM
-  _delete_domain rd-undercloud-$NUM-cert-test
+  delete_domain rd-undercloud-$NUM
+  delete_domain rd-undercloud-$NUM-cert-test
 }
 
 function delete_volume() {
@@ -242,5 +330,14 @@ function rhel_unregister_system() {
   if [[ -f $image_file ]] ; then
     virt-customize -a $image_file \
       --run-command "subscription-manager unregister"
+  fi
+}
+
+function assert_env_exists() {
+  local name=$1
+  if virsh list --all | grep -q "$name" ; then
+    echo 'ERROR: environment present. please clean up first'
+    virsh list --all | grep "$name"
+    exit 1
   fi
 }
