oshelm: ssh fixes

diff --git a/common/virsh/functions b/common/virsh/functions
--- a/common/virsh/functions
+++ b/common/virsh/functions
@@ -361,6 +361,9 @@ function rhel_unregister_system() {
 
 function domain_customize() {
   local domain=$1
+  local hname=${2:-${domain}}
+  local ssh_user=${3:-$(whoami)}
+  # ssu_user could be root:file:/home/jenkins/.ssh/id_rsa.pub
   virt-customize -d $domain \
     --run-command 'xfs_growfs /' \
     --run-command 'systemctl enable sshd' \
@@ -368,10 +371,11 @@ function domain_customize() {
     --root-password password:qwe123QWE \
     --run-command 'yum remove -y cloud-init' \
     --run-command 'echo net.ipv6.conf.all.disable_ipv6=1 >> /etc/sysctl.conf' \
-    --run-command 'echo net.ipv6.conf.all.disable_ipv6=1 >> /etc/sysctl.conf' \
+    --run-command 'echo net.ipv6.conf.default.disable_ipv6=1 >> /etc/sysctl.conf' \
     --run-command 'cd /etc/sysconfig/network-scripts && sed 's/eth0/ens3/g' ifcfg-eth0 > ifcfg-ens3' \
+    --hostname $hname \
+    --ssh-inject $ssh_user \
     --selinux-relabel
-
 }
 
 function assert_env_exists() {
@@ -381,4 +385,50 @@ function assert_env_exists() {
     virsh list --all | grep "$name"
     exit 1
   fi
+}
+
+function wait_dhcp() {
+  local net=$1
+  local host=${2:-''}
+  local max_iter=${3:-20}
+  local iter=0
+  local filter="ipv4"
+  if [[ -n "$host" ]] ; then
+    filter+=".*${host}"
+  fi
+  while true ; do
+    local ip=$(virsh net-dhcp-leases $net | grep "$filter" | awk '{print($5)}' | cut -d '/' -f 1)
+    if echo $ip | grep -q '[0-9]\.[0-9]\.[0-9]\.[0-9]' ; then
+      echo $ip
+      break
+    fi
+    if (( iter >= max_iter )) ; then
+      echo "Failed to wait ip address allocation via dhcp"
+      exit 1
+    fi
+    echo "Waiting for dhcp address requested... $iter"
+    sleep 30
+    ((++iter))
+  done
+}
+
+function wait_ssh() {
+  local addr=$1
+  local ssh_key=${2:-''}
+  local max_iter=${3:-20}
+  local iter=0
+  local ssh_opts='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
+  if [[ -n "$ssh_key" ]] ; then
+    ssh_opts+=" -i $ssh_key"
+  fi
+  truncate -s 0 ./tmp_file
+  while ! scp $ssh_opts -B ./tmp_file root@${addr}:/tmp/tmp_file ; do
+    if (( iter >= max_iter )) ; then
+      echo "Could not connect to undercloud"
+      exit 1
+    fi
+    echo "Waiting for undercloud..."
+    sleep 30
+    ((++iter))
+  done
 }
