ks8s: fixed error in wait for several dhcp addresses

diff --git a/common/virsh/functions b/common/virsh/functions
--- a/common/virsh/functions
+++ b/common/virsh/functions
@@ -403,24 +403,25 @@ function assert_env_exists() {
 
 function wait_dhcp() {
   local net=$1
-  local host=${2:-''}
-  local max_iter=${3:-20}
+  local count=${2:-1}
+  local host=${3:-''}
+  local max_iter=${4:-20}
   local iter=0
   local filter="ipv4"
   if [[ -n "$host" ]] ; then
     filter+=".*${host}"
   fi
   while true ; do
-    local ips=$(virsh net-dhcp-leases $net | grep "$filter" | awk '{print($5)}' | cut -d '/' -f 1)
-    if echo "$ips" | grep -q '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' ; then
-      echo "$ips"
+    local ips=( $(virsh net-dhcp-leases $net | sed 1,2d | grep "$filter" | awk '{print($5)}' | cut -d '/' -f 1) )
+    if (( ${#ips[@]} == count )) ; then
+      echo "${ips[@]}"
       break
     fi
     if (( iter >= max_iter )) ; then
-      echo "Failed to wait ip addresses allocation via dhcp" >&2
+      echo "Failed to wait for $count ip addresses allocation via dhcp" >&2
       exit 1
     fi
-    echo "Waiting for dhcp address requested... $iter" >&2
+    echo "Waiting for $count dhcp address requested... $iter" >&2
     sleep 30
     ((++iter))
   done
