containers: rework HA parameter to allow set different for different jobs

diff --git a/contrail-containers/helm/aws-defs b/contrail-containers/helm/aws-defs
--- a/contrail-containers/helm/aws-defs
+++ b/contrail-containers/helm/aws-defs
@@ -1,9 +1,12 @@
 export BUILD_NODE_TYPE=m4.large
+
 if [[ "$HA" == 'ha' ]] ; then
   export CONT_NODES=3
 else
-  export CONT_NODES=1
+  echo "ERROR: Non-HA and AIO deployments are not supported"
+  exit 1
 fi
+
 export CONT_NODE_TYPE=m4.xlarge
 export COMP_NODES=1
 export COMP_NODE_TYPE=c4.xlarge
