juju: rework & commonize code

diff --git a/juju/common/functions b/juju/common/functions
--- a/juju/common/functions
+++ b/juju/common/functions
@@ -142,23 +142,20 @@ function create_stackrc() {
   echo "export OS_PASSWORD=$PASSWORD" >> $WORKSPACE/stackrc
 }
 
-function open_port() {
-  local mch=$1
-  local port=$2
-  local protocol=${3:-tcp}
+function post_deploy() {
+  echo "INFO: Waiting for services start: $(date)"
 
-  for i in {0..30} ; do
-    local iid=`get-machine-id-by-number $mch`
-    if [[ "$iid" == i-* ]] ; then
-      break
-    fi
-    sleep 5
-  done
-
-  local sg_id=`aws ec2 describe-instances --instance-id "$iid" --query 'Reservations[*].Instances[*].SecurityGroups' | grep -C 2 "\-$mch\"" | awk '/GroupId/{print $2}' | head -1 | xargs`
-  if echo $sg_id | grep ',' ; then
-    sg_id=`echo $sg_id | sed 's/\,//g'`
+  if ! wait_absence_status_for_services "executing|blocked|waiting" 45 ; then
+    echo "ERROR: Waiting for services end: $(date)"
+    return 1
   fi
-  aws ec2 authorize-security-group-ingress --group-id $sg_id --protocol $protocol --port $port --cidr 0.0.0.0/0
-  aws ec2 describe-security-groups --group-id $sg_id
+  echo "INFO: Waiting for services end: $(date)"
+
+  # check for errors
+  if juju-status | grep "current" | grep error ; then
+    echo "ERROR: Some services went to error state"
+    return 1
+  fi
+
+  juju-status-tabular
 }
