choose correct security group for port open cmd

diff --git a/juju/common/functions-juju1 b/juju/common/functions-juju1
--- a/juju/common/functions-juju1
+++ b/juju/common/functions-juju1
@@ -64,6 +64,11 @@ function get-machine-ip-by-number() {
   exit 100
 }
 
+function get-machine-id-by-number() {
+  echo "ERROR: get-machine-id-by-number for juju 1.0 is not implemented"
+  exit 100
+}
+
 function juju-attach() {
   echo "ERROR: juju-attach is not available for juju 1.0"
   exit 100
