add ability to deploy contrail via bundle

diff --git a/juju/common/functions-juju1 b/juju/common/functions-juju1
--- a/juju/common/functions-juju1
+++ b/juju/common/functions-juju1
@@ -63,3 +63,8 @@ function get-machine-ip-by-number() {
   echo "ERROR: get-machine-ip-by-number for juju 1.0 is not implemented"
   exit 100
 }
+
+function juju-attach() {
+  echo "ERROR: juju-attach is not available for juju 1.0"
+  exit 100
+}
