juju: fix typo in check script

diff --git a/juju/common/functions-openstack b/juju/common/functions-openstack
--- a/juju/common/functions-openstack
+++ b/juju/common/functions-openstack
@@ -421,13 +421,13 @@ function check_instance_simple() {
 }
 
 function check_heat() {
-    echo "INFO: check heat resources"
-    if ! openstack orchestration resource type list | grep ContrailV2 ; then
-      echo "ERROR: Contrail's heat resouces not found!"
-      openstack orchestration resource type list
-      ret=1
-    fi
-    cat >$WORKSPACE/ipam.yaml <<EOF
+  echo "INFO: check heat resources"
+  if ! openstack orchestration resource type list | grep ContrailV2 ; then
+    echo "ERROR: Contrail's heat resouces not found!"
+    openstack orchestration resource type list
+    ret=1
+  fi
+  cat >$WORKSPACE/ipam.yaml <<EOF
 heat_template_version: 2013-05-23
 
 description: >
@@ -445,23 +445,23 @@ resources:
       name: { get_param: ipam_name }
 EOF
 
-    local fx=$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 4)
-    if ! openstack stack create -t $WORKSPACE/ipam.yaml/ipam.yaml --parameter ipam_name=testipam teststack-$sfx
-      echo "ERROR: Heat resouce creation failed!"
-      openstack stack list
-      ret=1
-    fi
-    sleep 5
-    local status
-    if ! status=$(openstack stack show teststack-$sfx | awk '/stack_status /{print $4}') ; then
-      echo "ERROR: Heat resouce retreiving failed!"
-      openstack stack list
-      ret=1
-    fi
-    if [[ $status != "CREATE_COMPLETE" ]]; then
-      echo "ERROR: Heat resouce creation failed!"
-      openstack stack show teststack-$sfx
-      ret=1
-    fi
-    echo "INFO: check heat passed"
+  local fx=$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 4)
+  if ! openstack stack create -t $WORKSPACE/ipam.yaml/ipam.yaml --parameter ipam_name=testipam teststack-$sfx ; then
+    echo "ERROR: Heat resouce creation failed!"
+    openstack stack list
+    ret=1
+  fi
+  sleep 5
+  local status
+  if ! status=$(openstack stack show teststack-$sfx | awk '/stack_status /{print $4}') ; then
+    echo "ERROR: Heat resouce retreiving failed!"
+    openstack stack list
+    ret=1
+  fi
+  if [[ $status != "CREATE_COMPLETE" ]]; then
+    echo "ERROR: Heat resouce creation failed!"
+    openstack stack show teststack-$sfx
+    ret=1
+  fi
+  echo "INFO: check heat passed"
 }
