add ssh/get instance metadata tests

diff --git a/juju/common/functions-openstack b/juju/common/functions-openstack
--- a/juju/common/functions-openstack
+++ b/juju/common/functions-openstack
@@ -1,4 +1,4 @@
-# /bin/bash
+#!/bin/bash
 
 MAX_FAIL=30
 
@@ -134,10 +134,6 @@ function create_network() {
   openstack --insecure router set --external-gateway $public_net_id $router_id
   openstack --insecure router add subnet $router_id $private_subnet_id
 
-  for mch in `juju-status-tabular nova-compute | grep -A 6 "^Machine " | tail -n +2 | grep -B 6 "^$" | head -n -1 | awk '{print $1}'` ; do
-    juju-ssh $mch sudo /opt/contrail/utils/provision_vgw_interface.py --oper create --interface vgw --subnets 10.5.0.0/24 --routes 0.0.0.0/0 --vrf default-domain:admin:public-$netsfx:public-$netsfx
-  done
-
   deactivate_venv
 }
 
@@ -209,16 +205,17 @@ function _check_instance_log() {
     echo "ERROR: console log is empty for instance $instance_id"
     return 1
   fi
+  echo '>>>>>>>>>'
   openstack --insecure console log show $id | tail -50
+  echo '<<<<<<<<<'
   return 0
 }
 
 function _get_instance_machine() {
   local id=$1
-  local host=`openstack --insecure server show $id | grep "$host_attr" | awk '{print $4}'`
-  local ip=`openstack --insecure hypervisor show -f value -c host_ip $host`
-  local mch=`get_machine_by_ip $ip`
-  echo $mch
+  local host=`openstack --insecure server list --long -c ID -c Host | grep $id | awk '{print $4}'`
+  local ip=`nslookup $host | awk '/Address/{print $2}' | tail -1`
+  get_machine_by_ip $ip
 }
 
 function _check_new_route() {
@@ -234,12 +231,32 @@ function _check_new_route() {
 
 function _check_instance_ping() {
   local mch=$1
-  local fip=$2
-  if ! juju-ssh $mch ping -c 2 $fip 2>/dev/null ; then
-    echo "ERROR: Can't ping instance by ip $fip"
+  local ip=$2
+  if ! juju-ssh $mch ping -c 2 $ip 2>/dev/null ; then
+    echo "ERROR: Can't ping instance by ip $ip"
     return 1
   fi
-  echo "INFO: Can ping instance by ip $fip"
+  echo "INFO: Can ping instance by ip $ip"
+  return 0
+}
+
+function _check_instance_ssh_and_metadata() {
+  local mch=$1
+  local ip=$2
+  local ssh_opts='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
+  juju-ssh sudo apt-get -y install sshpass
+  echo "INFO: Trying to ssh into instance with ip $ip"
+  if ! juju-ssh $mch sshpass 'cubswin:)' ssh $ssh_opts cirros@$ip ifconfig 2>/dev/null ; then
+    echo "ERROR: Can't ssh into instance by ip $ip"
+    return 1
+  fi
+
+  echo "INFO: Trying to ssh into instance with ip $ip and get meta-data/public-ipv4"
+  if ! juju-ssh $mch sshpass 'cubswin:)' ssh $ssh_opts cirros@$ip curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null ; then
+    echo "ERROR: Can't get instance metadata by ssh into ip $ip"
+    return 1
+  fi
+  echo "INFO: Can ssh and get metadata for instance by ip $ip"
   return 0
 }
 
@@ -249,8 +266,10 @@ function check_instance_simple() {
   local net_id=$1
   local fip=$2
 
+  set -x
+
   declare -a rts
-  for mch in `juju-status-tabular nova-compute | grep -A 6 "^Machine " | tail -n +2 | grep -B 6 "^$" | head -n -1 | awk '{print $1}'` ; do
+  for mch in `get_machine_index_by_service nova-compute` ; do
     rts[$mch]=`_get_current_routes $mch`
   done
 
@@ -276,12 +295,26 @@ function check_instance_simple() {
       local new_route="$r"
       break
     done
-    echo "INFO: Instance's new route is $new_route"
+    if [[ -n $new_route ]] ; then
+      echo "INFO: Instance's new route is $new_route"
+      _check_new_route $mch $new_route || ret=1
+    else
+      echo "INFO: Couldn't find new route 169.254.0.*"
+      ret=1
+    fi
 
-    _check_new_route $mch $new_route || ret=1
     _check_instance_ping $mch $new_route || ret=1
-    _check_instance_ping $mch $fip || ret=1
-    #_check_instance_ssh $instance_id || ret=1
+    _check_instance_ssh_and_metadata $mch $new_route || ret=1
+
+    # add VGW to second compute host and check ping/ssh from there
+    another_compute_host=`get_machine_index_by_service nova-compute | grep -v $mch`
+    juju-ssh $another_compute_host sudo /opt/contrail/utils/provision_vgw_interface.py --oper create --interface vgw --subnets 10.5.0.0/24 --routes 0.0.0.0/0 --vrf default-domain:admin:public-$netsfx:public-$netsfx
+
+    _check_instance_ping $another_compute_host $fip || ret=1
+    _check_instance_ssh_and_metadata $another_compute_host $fip || ret=1
+
+    # remove VGW
+    juju-ssh $another_compute_host sudo /opt/contrail/utils/provision_vgw_interface.py --oper delete --interface vgw --subnets 10.5.0.0/24 --routes 0.0.0.0/0 --vrf default-domain:admin:public-$netsfx:public-$netsfx
   fi
 
   openstack --insecure server show $instance_id
